# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  #push:
    #branches: [main]
    #- "[Ff]eature-*" 
  pull_request:
    types: [closed]
    branches: [ main ]
    #- "[Ff]eature-*" 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest #windows-latest #ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
         fetch-depth: "0"
         
      - id: changedFiles
        uses: jitterbit/get-changed-files@v1
      
      - name: '' #get changed files
        id: getfile
        run: |
          chmod +x .github/workflows/changedFilesFilter.sh
          awk '{ sub("\r$", ""); print }' .github/workflows/changedFilesFilter.sh > .github/workflows/changedFilesFilter2.sh
          mv .github/workflows/changedFilesFilter2.sh .github/workflows/changedFilesFilter.sh
          chmod +x .github/workflows/changedFilesFilter.sh
          echo "::set-output name=files::$(.github/workflows/changedFilesFilter.sh "${{ steps.changedFiles.outputs.added_modified }}")"
     
      - name: echo output
        run: |
         echo ${{ steps.getfile.outputs.files }}
      
      #- name: Create issue using REST API
        #run: |
          #curl --request POST \
          #--url https://api.github.com/repos/${{ github.repository }}/issues \
          #--header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          #--header 'content-type: application/json' \
          #--data '{
          #  "title": "Automated issue for commit: ${{ github.sha }}",
          #  "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
          #  }'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
